### ISSUE TITLE
rhel changes

### ISSUE THREAD

**Issue by hoonetorg** [bechtoldt/saltstack-binddns-formula#4]
Hi, this time the other way around, as proposed in the readme :).
Can you have a look at my changes for el7.
I changed a few file locations, to make this formula work with selinux in enforcing mode.
Additionally I need to put static db files to /var/named(which is the standard for el afaiu) because I need write permission on /var/named/data for the log files (the formula would remove write perms on that dir, if used for db-files).

Keep on with your great formulas

**Comment by hoonetorg** [comment]
here is a snippet of my pillar data:
https://gist.github.com/hoonetorg/f380063e2b03105f4881

there is a 

```
        includes:
          - /etc/named.root.key
```

The easiest (and-not-so-clean) way to have that file included per default is putting this 2lines into binddns/default.yaml. You probably have a better proposal :)

**Comment by arnisoph** [comment]
Hi, when you already pushed code to Github, please create a PR. :)

The remark in the README file is for those who plan to make large code changes in the future.
